include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [build/**,test_resources/**]
  strong-mode:
    implicit-casts: false
  errors:
    omit_local_variable_types: ignore
linter:
  rules:
    avoid_empty_else: true
    avoid_print: true
    prefer_single_quotes: true