include: package:pedantic/analysis_options.yaml

analyzer:
  exclude: [build/**,test_resources/**]
  strong-mode:
    implicit-casts: false
  errors:
    omit_local_variable_types: ignore
  enable-experiment:
    - non-nullable
linter:
  rules:
    - avoid_empty_else